/**
 * Bangladesh Administrative Divisions, Districts, and Upazilas / Thanas Data
 * 8 Divisions -> 64 Districts -> Upazilas / Thanas
 */

export interface UpazilaOption {
  id: string;
  name: string;
  bnName: string;
}

export interface DistrictOption {
  id: string;
  name: string;
  bnName: string;
  isDhakaCity?: boolean;
  upazilas: UpazilaOption[];
}

export interface DivisionOption {
  id: string;
  name: string;
  bnName: string;
  districts: DistrictOption[];
}

export const BANGLADESH_DIVISIONS: DivisionOption[] = [
  {
    id: 'dhaka',
    name: 'Dhaka Division',
    bnName: 'ঢাকা বিভাগ',
    districts: [
      {
        id: 'dhaka',
        name: 'Dhaka',
        bnName: 'ঢাকা',
        isDhakaCity: true,
        upazilas: [
          { id: 'gulshan', name: 'Gulshan', bnName: 'গুলশান' },
          { id: 'banani', name: 'Banani', bnName: 'বনানী' },
          { id: 'mohakhali', name: 'Mohakhali', bnName: 'মহাখালী' },
          { id: 'dhanmondi', name: 'Dhanmondi', bnName: 'ধানমন্ডি' },
          { id: 'uttara', name: 'Uttara', bnName: 'উত্তরা' },
          { id: 'mirpur', name: 'Mirpur', bnName: 'মিরপুর' },
          { id: 'mohammadpur', name: 'Mohammadpur', bnName: 'মোহাম্মদপুর' },
          { id: 'badda', name: 'Badda', bnName: 'বাড্ডা' },
          { id: 'motijheel', name: 'Motijheel', bnName: 'মতিঝিল' },
          { id: 'tejgaon', name: 'Tejgaon', bnName: 'তেজগাঁও' },
          { id: 'khilgaon', name: 'Khilgaon', bnName: 'খিলগাঁও' },
          { id: 'rampura', name: 'Rampura', bnName: 'রামপুরা' },
          { id: 'jatrabari', name: 'Jatrabari', bnName: 'যাত্রাবাড়ী' },
          { id: 'lalbagh', name: 'Lalbagh', bnName: 'লালবাগ' },
          { id: 'shahbagh', name: 'Shahbagh', bnName: 'শাহবাগ' },
          { id: 'paltan', name: 'Paltan', bnName: 'পল্টন' },
          { id: 'bashundhara', name: 'Bashundhara R/A', bnName: 'বসুন্ধরা আ/এ' },
          { id: 'savar', name: 'Savar', bnName: 'সাভার' },
          { id: 'dhamrai', name: 'Dhamrai', bnName: 'ধামরাই' },
          { id: 'keraniganj', name: 'Keraniganj', bnName: 'কেরানীগঞ্জ' },
          { id: 'dohar', name: 'Dohar', bnName: 'দোহার' },
          { id: 'nawabganj', name: 'Nawabganj', bnName: 'নবাবগঞ্জ' },
        ],
      },
      {
        id: 'gazipur',
        name: 'Gazipur',
        bnName: 'গাজীপুর',
        upazilas: [
          { id: 'gazipur-sadar', name: 'Gazipur Sadar', bnName: 'গাজীপুর সদর' },
          { id: 'tongi', name: 'Tongi', bnName: 'টঙ্গী' },
          { id: 'kaliakair', name: 'Kaliakair', bnName: 'কালিয়াকৈর' },
          { id: 'kapasia', name: 'Kapasia', bnName: 'কাপাসিয়া' },
          { id: 'sreepur', name: 'Sreepur', bnName: 'শ্রীপুর' },
          { id: 'kaliganj', name: 'Kaliganj', bnName: 'কালীগঞ্জ' },
        ],
      },
      {
        id: 'narayanganj',
        name: 'Narayanganj',
        bnName: 'নারায়ণগঞ্জ',
        upazilas: [
          { id: 'narayanganj-sadar', name: 'Narayanganj Sadar', bnName: 'নারায়ণগঞ্জ সদর' },
          { id: 'fatullah', name: 'Fatullah', bnName: 'ফতুল্লা' },
          { id: 'siddhirganj', name: 'Siddhirganj', bnName: 'সিদ্ধিরগঞ্জ' },
          { id: 'bandar', name: 'Bandar', bnName: 'বন্দর' },
          { id: 'rupganj', name: 'Rupganj', bnName: 'রূপগঞ্জ' },
          { id: 'araihazar', name: 'Araihazar', bnName: 'আড়াইহাজার' },
          { id: 'sonargaon', name: 'Sonargaon', bnName: 'সোনারগাঁও' },
        ],
      },
      {
        id: 'tangail',
        name: 'Tangail',
        bnName: 'টাঙ্গাইল',
        upazilas: [
          { id: 'tangail-sadar', name: 'Tangail Sadar', bnName: 'টাঙ্গাইল সদর' },
          { id: 'gopalpur', name: 'Gopalpur', bnName: 'গোপালপুর' },
          { id: 'basail', name: 'Basail', bnName: 'বাসাইল' },
          { id: 'bhuapur', name: 'Bhuapur', bnName: 'ভূঞাপুর' },
          { id: 'delduar', name: 'Delduar', bnName: 'দেলদুয়ার' },
          { id: 'ghatail', name: 'Ghatail', bnName: 'ঘাটাইল' },
          { id: 'kalihati', name: 'Kalihati', bnName: 'কালিহাতী' },
          { id: 'madhupur', name: 'Madhupur', bnName: 'মধুপুর' },
          { id: 'mirzapur', name: 'Mirzapur', bnName: 'মির্জাপুর' },
          { id: 'nagarpur', name: 'Nagarpur', bnName: 'নাগরপুর' },
          { id: 'sakhipur', name: 'Sakhipur', bnName: 'সখিপুর' },
          { id: 'dhanbari', name: 'Dhanbari', bnName: 'ধনবাড়ী' },
        ],
      },
      {
        id: 'faridpur',
        name: 'Faridpur',
        bnName: 'ফরিদপুর',
        upazilas: [
          { id: 'faridpur-sadar', name: 'Faridpur Sadar', bnName: 'ফরিদপুর সদর' },
          { id: 'boalmari', name: 'Boalmari', bnName: 'বোয়ালমারী' },
          { id: 'alfadanga', name: 'Alfadanga', bnName: 'আলফাডাঙ্গা' },
          { id: 'madhukhali', name: 'Madhukhali', bnName: 'মধুখালী' },
          { id: 'bhanga', name: 'Bhanga', bnName: 'ভাঙ্গা' },
          { id: 'nagarkanda', name: 'Nagarkanda', bnName: 'নগরকান্দা' },
          { id: 'charbhadrasan', name: 'Charbhadrasan', bnName: 'চরভদ্রাসন' },
          { id: 'sadarpur', name: 'Sadarpur', bnName: 'সদরপুর' },
          { id: 'saltha', name: 'Saltha', bnName: 'সালথা' },
        ],
      },
      {
        id: 'manikganj',
        name: 'Manikganj',
        bnName: 'মানিকগঞ্জ',
        upazilas: [
          { id: 'manikganj-sadar', name: 'Manikganj Sadar', bnName: 'মানিকগঞ্জ সদর' },
          { id: 'singair', name: 'Singair', bnName: 'সিংগাইর' },
          { id: 'shibalaya', name: 'Shibalaya', bnName: 'শিবালয়' },
          { id: 'saturia', name: 'Saturia', bnName: 'সাটুরিয়া' },
          { id: 'harirampur', name: 'Harirampur', bnName: 'হরিরামপুর' },
          { id: 'ghior', name: 'Ghior', bnName: 'ঘিওরে' },
          { id: 'daulatpur', name: 'Daulatpur', bnName: 'দৌলতপুর' },
        ],
      },
      {
        id: 'munshiganj',
        name: 'Munshiganj',
        bnName: 'মুন্সীগঞ্জ',
        upazilas: [
          { id: 'munshiganj-sadar', name: 'Munshiganj Sadar', bnName: 'মুন্সীগঞ্জ সদর' },
          { id: 'tongibari', name: 'Tongibari', bnName: 'টংগীবাড়ী' },
          { id: 'sreenagar', name: 'Sreenagar', bnName: 'শ্রীনগর' },
          { id: 'louhajang', name: 'Louhajang', bnName: 'লৌহজং' },
          { id: 'gajaria', name: 'Gajaria', bnName: 'গজারিয়া' },
          { id: 'sirajdikhan', name: 'Sirajdikhan', bnName: 'সিরাজদিখান' },
        ],
      },
      {
        id: 'narsingdi',
        name: 'Narsingdi',
        bnName: 'নরসিংদী',
        upazilas: [
          { id: 'narsingdi-sadar', name: 'Narsingdi Sadar', bnName: 'নরসিংদী সদর' },
          { id: 'belabo', name: 'Belabo', bnName: 'বেলাবো' },
          { id: 'monohardi', name: 'Monohardi', bnName: 'মনোহরদী' },
          { id: 'palash', name: 'Palash', bnName: 'পলাশ' },
          { id: 'raipura', name: 'Raipura', bnName: 'রায়পুরা' },
          { id: 'shibpur', name: 'Shibpur', bnName: 'শিবপুর' },
        ],
      },
      {
        id: 'kishoreganj',
        name: 'Kishoreganj',
        bnName: 'কিশোরগঞ্জ',
        upazilas: [
          { id: 'kishoreganj-sadar', name: 'Kishoreganj Sadar', bnName: 'কিশোরগঞ্জ সদর' },
          { id: 'bajitpur', name: 'Bajitpur', bnName: 'বাজিতপুর' },
          { id: 'bhairab', name: 'Bhairab', bnName: 'ভৈরব' },
          { id: 'hossainpur', name: 'Hossainpur', bnName: 'হোসেনপুর' },
          { id: 'itna', name: 'Itna', bnName: 'ইটনা' },
          { id: 'karimganj', name: 'Karimganj', bnName: 'করিমগঞ্জ' },
          { id: 'katiadi', name: 'Katiadi', bnName: 'কটিয়াদী' },
          { id: 'kuliarchar', name: 'Kuliarchar', bnName: 'কুলিয়ারচর' },
          { id: 'mithamain', name: 'Mithamain', bnName: 'মিঠামইন' },
          { id: 'nikli', name: 'Nikli', bnName: 'নিকলী' },
          { id: 'pakundia', name: 'Pakundia', bnName: 'পাকুন্দিয়া' },
          { id: 'tarail', name: 'Tarail', bnName: 'তাড়াইল' },
        ],
      },
      {
        id: 'gopalganj',
        name: 'Gopalganj',
        bnName: 'গোপালগঞ্জ',
        upazilas: [
          { id: 'gopalganj-sadar', name: 'Gopalganj Sadar', bnName: 'গোপালগঞ্জ সদর' },
          { id: 'kashiani', name: 'Kashiani', bnName: 'কাশিয়ানী' },
          { id: 'kotalipara', name: 'Kotalipara', bnName: 'কোটালীপাড়া' },
          { id: 'muksudpur', name: 'Muksudpur', bnName: 'মুকসুদপুর' },
          { id: 'tungipara', name: 'Tungipara', bnName: 'টুঙ্গিপাড়া' },
        ],
      },
      {
        id: 'madaripur',
        name: 'Madaripur',
        bnName: 'মাদারীপুর',
        upazilas: [
          { id: 'madaripur-sadar', name: 'Madaripur Sadar', bnName: 'মাদারীপুর সদর' },
          { id: 'kalkini', name: 'Kalkini', bnName: 'কালকিনি' },
          { id: 'rajoir', name: 'Rajoir', bnName: 'রাজৈর' },
          { id: 'shibchar', name: 'Shibchar', bnName: 'শিবচর' },
          { id: 'dasar', name: 'Dasar', bnName: 'ডাসার' },
        ],
      },
      {
        id: 'rajbari',
        name: 'Rajbari',
        bnName: 'রাজবাড়ী',
        upazilas: [
          { id: 'rajbari-sadar', name: 'Rajbari Sadar', bnName: 'রাজবাড়ী সদর' },
          { id: 'baliakandi', name: 'Baliakandi', bnName: 'বালিয়াকান্দি' },
          { id: 'goalandaghat', name: 'Goalanda Ghat', bnName: 'গোয়ালন্দঘাট' },
          { id: 'pangsha', name: 'Pangsha', bnName: 'পাংশা' },
          { id: 'kalukhali', name: 'Kalukhali', bnName: 'কালুখালী' },
        ],
      },
      {
        id: 'shariatpur',
        name: 'Shariatpur',
        bnName: 'শরীয়তপুর',
        upazilas: [
          { id: 'shariatpur-sadar', name: 'Shariatpur Sadar', bnName: 'শরীয়তপুর সদর' },
          { id: 'damudya', name: 'Damudya', bnName: 'ডামুড্যা' },
          { id: 'naria', name: 'Naria', bnName: 'নড়িয়া' },
          { id: 'jajira', name: 'Jajira', bnName: 'জাজিরা' },
          { id: 'bhedarganj', name: 'Bhedarganj', bnName: 'ভেদরগঞ্জ' },
          { id: 'gosairhat', name: 'Gosairhat', bnName: 'গোসাইরহাট' },
        ],
      },
    ],
  },
  {
    id: 'chattogram',
    name: 'Chattogram Division',
    bnName: 'চট্টগ্রাম বিভাগ',
    districts: [
      {
        id: 'chattogram',
        name: 'Chattogram',
        bnName: 'চট্টগ্রাম',
        upazilas: [
          { id: 'agrabad', name: 'Agrabad', bnName: 'আগ্রাবাদ' },
          { id: 'kotwali-ctg', name: 'Kotwali', bnName: 'কোতোয়ালী' },
          { id: 'panchlaish', name: 'Panchlaish', bnName: 'পাঁচলাইশ' },
          { id: 'halishahar', name: 'Halishahar', bnName: 'হালিশহর' },
          { id: 'khulshi', name: 'Khulshi', bnName: 'খুলশী' },
          { id: 'patenga', name: 'Patenga', bnName: 'পতেঙ্গা' },
          { id: 'chandgaon', name: 'Chandgaon', bnName: 'চান্দগাঁও' },
          { id: 'bakalia', name: 'Bakalia', bnName: 'বাকলিয়া' },
          { id: 'sitakunda', name: 'Sitakunda', bnName: 'সীতাকুণ্ড' },
          { id: 'mirsharai', name: 'Mirsharai', bnName: 'মীরসরাই' },
          { id: 'hathazari', name: 'Hathazari', bnName: 'হাটহাজারী' },
          { id: 'raozan', name: 'Raozan', bnName: 'রাউজান' },
          { id: 'patiya', name: 'Patiya', bnName: 'পটিয়া' },
          { id: 'boalkhali', name: 'Boalkhali', bnName: 'বোয়ালখালী' },
          { id: 'anwara', name: 'Anwara', bnName: 'আনোয়ারা' },
          { id: 'sandwip', name: 'Sandwip', bnName: 'সন্দ্বীপ' },
          { id: 'satkania', name: 'Satkania', bnName: 'সাতকানিয়া' },
          { id: 'lohagara-ctg', name: 'Lohagara', bnName: 'লোহাগাড়া' },
          { id: 'banshkhali', name: 'Banshkhali', bnName: 'বাঁশখালী' },
        ],
      },
      {
        id: 'coxs-bazar',
        name: "Cox's Bazar",
        bnName: 'কক্সবাজার',
        upazilas: [
          { id: 'coxs-bazar-sadar', name: "Cox's Bazar Sadar", bnName: 'কক্সবাজার সদর' },
          { id: 'chakaria', name: 'Chakaria', bnName: 'চকরিয়া' },
          { id: 'maheshkhali', name: 'Maheshkhali', bnName: 'মহেশখালী' },
          { id: 'teknaf', name: 'Teknaf', bnName: 'টেকনাফ' },
          { id: 'ramu', name: 'Ramu', bnName: 'রামু' },
          { id: 'ukhiya', name: 'Ukhiya', bnName: 'উখিয়া' },
          { id: 'pekua', name: 'Pekua', bnName: 'পেকুয়া' },
          { id: 'kutubdia', name: 'Kutubdia', bnName: 'কুতুবদিয়া' },
        ],
      },
      {
        id: 'cumilla',
        name: 'Cumilla',
        bnName: 'কুমিল্লা',
        upazilas: [
          { id: 'cumilla-adarsha-sadar', name: 'Adarsha Sadar', bnName: 'আদর্শ সদর' },
          { id: 'cumilla-sadar-south', name: 'Sadar South', bnName: 'সদর দক্ষিণ' },
          { id: 'daudkandi', name: 'Daudkandi', bnName: 'দাউদকান্দি' },
          { id: 'chandina', name: 'Chandina', bnName: 'চান্দিনা' },
          { id: 'muradnagar', name: 'Muradnagar', bnName: 'মুরাদনগর' },
          { id: 'debidwar', name: 'Debidwar', bnName: 'দেবীদ্বার' },
          { id: 'burichang', name: 'Burichang', bnName: 'বুড়িচং' },
          { id: 'brahmanpara', name: 'Brahmanpara', bnName: 'ব্রাহ্মণপাড়া' },
          { id: 'laksam', name: 'Laksam', bnName: 'লাকসাম' },
          { id: 'chauddagram', name: 'Chauddagram', bnName: 'চৌদ্দগ্রাম' },
          { id: 'nangalkot', name: 'Nangalkot', bnName: 'নাঙ্গলকোট' },
          { id: 'barura', name: 'Barura', bnName: 'বরুড়া' },
        ],
      },
      {
        id: 'brahmanbaria',
        name: 'Brahmanbaria',
        bnName: 'ব্রাহ্মণবাড়িয়া',
        upazilas: [
          { id: 'brahmanbaria-sadar', name: 'Brahmanbaria Sadar', bnName: 'ব্রাহ্মণবাড়িয়া সদর' },
          { id: 'ashuganj', name: 'Ashuganj', bnName: 'আশুগঞ্জ' },
          { id: 'nasirnagar', name: 'Nasirnagar', bnName: 'নাসিরনগর' },
          { id: 'nabinagar', name: 'Nabinagar', bnName: 'নবীনগর' },
          { id: 'sarail', name: 'Sarail', bnName: 'সরাইল' },
          { id: 'kasba', name: 'Kasba', bnName: 'কসবা' },
          { id: 'akhaura', name: 'Akhaura', bnName: 'আখাউড়া' },
          { id: 'bancharampur', name: 'Bancharampur', bnName: 'বাঞ্ছারামপুর' },
          { id: 'bijoynagar', name: 'Bijoynagar', bnName: 'বিজয়নগর' },
        ],
      },
      {
        id: 'feni',
        name: 'Feni',
        bnName: 'ফেনী',
        upazilas: [
          { id: 'feni-sadar', name: 'Feni Sadar', bnName: 'ফেনী সদর' },
          { id: 'daganbhuiyan', name: 'Daganbhuiyan', bnName: 'দাগনভূঁঞা' },
          { id: 'chhagalnaiya', name: 'Chhagalnaiya', bnName: 'ছাগলনাইয়া' },
          { id: 'parshuram', name: 'Parshuram', bnName: 'পরশুরাম' },
          { id: 'sonagazi', name: 'Sonagazi', bnName: 'সোনাগাজী' },
          { id: 'fulgazi', name: 'Fulgazi', bnName: 'ফুলগাজী' },
        ],
      },
      {
        id: 'noakhali',
        name: 'Noakhali',
        bnName: 'নোয়াখালী',
        upazilas: [
          { id: 'noakhali-sadar', name: 'Noakhali Sadar', bnName: 'নোয়াখালী সদর' },
          { id: 'begumganj', name: 'Begumganj', bnName: 'বেগমগঞ্জ' },
          { id: 'chatkhil', name: 'Chatkhil', bnName: 'চাটখিল' },
          { id: 'companiganj-noa', name: 'Companiganj', bnName: 'কোম্পানীগঞ্জ' },
          { id: 'hatiya', name: 'Hatiya', bnName: 'হাতিয়া' },
          { id: 'senbagh', name: 'Senbagh', bnName: 'সেনবাগ' },
          { id: 'sonaimuri', name: 'Sonaimuri', bnName: 'সোনাইমুড়ী' },
          { id: 'subarnachar', name: 'Subarnachar', bnName: 'সুবর্ণচর' },
          { id: 'kabirhat', name: 'Kabirhat', bnName: 'কবিরহাট' },
        ],
      },
      {
        id: 'lakshmipur',
        name: 'Lakshmipur',
        bnName: 'লক্ষ্মীপুর',
        upazilas: [
          { id: 'lakshmipur-sadar', name: 'Lakshmipur Sadar', bnName: 'লক্ষ্মীপুর সদর' },
          { id: 'raipur', name: 'Raipur', bnName: 'রায়পুর' },
          { id: 'ramganj', name: 'Ramganj', bnName: 'রামগঞ্জ' },
          { id: 'ramgati', name: 'Ramgati', bnName: 'রামগতি' },
          { id: 'kamalnagar', name: 'Kamalnagar', bnName: 'কমলনগর' },
        ],
      },
      {
        id: 'chandpur',
        name: 'Chandpur',
        bnName: 'চাঁদপুর',
        upazilas: [
          { id: 'chandpur-sadar', name: 'Chandpur Sadar', bnName: 'চাঁদপুর সদর' },
          { id: 'faridganj', name: 'Faridganj', bnName: 'ফরিদগঞ্জ' },
          { id: 'haimchar', name: 'Haimchar', bnName: 'হাইমচর' },
          { id: 'haziganj', name: 'Haziganj', bnName: 'হাজীগঞ্জ' },
          { id: 'kachua-chandpur', name: 'Kachua', bnName: 'কচুয়া' },
          { id: 'matlab-north', name: 'Matlab North', bnName: 'মতলব উত্তর' },
          { id: 'matlab-south', name: 'Matlab South', bnName: 'মতলব দক্ষিণ' },
          { id: 'shahrasti', name: 'Shahrasti', bnName: 'শাহরাস্তি' },
        ],
      },
      {
        id: 'khagrachhari',
        name: 'Khagrachhari',
        bnName: 'খাগড়াছড়ি',
        upazilas: [
          { id: 'khagrachhari-sadar', name: 'Khagrachhari Sadar', bnName: 'খাগড়াছড়ি সদর' },
          { id: 'dighinala', name: 'Dighinala', bnName: 'দিঘীনালা' },
          { id: 'panchhari', name: 'Panchhari', bnName: 'পানছড়ি' },
          { id: 'mahalchhari', name: 'Mahalchhari', bnName: 'মহালছড়ি' },
          { id: 'matiranga', name: 'Matiranga', bnName: 'মাটিরাঙ্গা' },
          { id: 'manikchhari', name: 'Manikchhari', bnName: 'মানিকছড়ি' },
          { id: 'ramgarh', name: 'Ramgarh', bnName: 'রামগড়' },
        ],
      },
      {
        id: 'rangamati',
        name: 'Rangamati',
        bnName: 'রাঙ্গামাটি',
        upazilas: [
          { id: 'rangamati-sadar', name: 'Rangamati Sadar', bnName: 'রাঙ্গামাটি সদর' },
          { id: 'kaptai', name: 'Kaptai', bnName: 'কাপ্তাই' },
          { id: 'baghaichhari', name: 'Baghaichhari', bnName: 'বাঘাইছড়ি' },
          { id: 'barkal', name: 'Barkal', bnName: 'বরকল' },
          { id: 'langadu', name: 'Langadu', bnName: 'লংগদু' },
          { id: 'rajasthali', name: 'Rajasthali', bnName: 'রাজস্থলী' },
        ],
      },
      {
        id: 'bandarban',
        name: 'Bandarban',
        bnName: 'বান্দরবান',
        upazilas: [
          { id: 'bandarban-sadar', name: 'Bandarban Sadar', bnName: 'বান্দরবান সদর' },
          { id: 'alikadam', name: 'Alikadam', bnName: 'আলীকদম' },
          { id: 'naikhongchhari', name: 'Naikhongchhari', bnName: 'নাইক্ষ্যংছড়ি' },
          { id: 'rowangchhari', name: 'Rowangchhari', bnName: 'রোয়াংছড়ি' },
          { id: 'ruma', name: 'Ruma', bnName: 'রুমা' },
          { id: 'thanchi', name: 'Thanchi', bnName: 'থানচি' },
          { id: 'lama', name: 'Lama', bnName: 'লামা' },
        ],
      },
    ],
  },
  {
    id: 'rajshahi',
    name: 'Rajshahi Division',
    bnName: 'রাজশাহী বিভাগ',
    districts: [
      {
        id: 'rajshahi',
        name: 'Rajshahi',
        bnName: 'রাজশাহী',
        upazilas: [
          { id: 'boalia', name: 'Boalia', bnName: 'বোয়ালিয়া' },
          { id: 'motihar', name: 'Motihar', bnName: 'মতিহার' },
          { id: 'rajputra', name: 'Rajpara', bnName: 'রাজপাড়া' },
          { id: 'shah-makhdum', name: 'Shah Makhdum', bnName: 'শাহ মখদুম' },
          { id: 'paba', name: 'Paba', bnName: 'পবা' },
          { id: 'durgapur-raj', name: 'Durgapur', bnName: 'দুর্গাপুর' },
          { id: 'bagmara', name: 'Bagmara', bnName: 'বাগমারা' },
          { id: 'charghat', name: 'Charghat', bnName: 'চারঘাট' },
          { id: 'puthia', name: 'Puthia', bnName: 'পুঠিয়া' },
          { id: 'godagari', name: 'Godagari', bnName: 'গোদাগাড়ী' },
          { id: 'tanore', name: 'Tanore', bnName: 'তানোর' },
          { id: 'mohanpur', name: 'Mohanpur', bnName: 'মোহনপুর' },
        ],
      },
      {
        id: 'bogura',
        name: 'Bogura',
        bnName: 'বগুড়া',
        upazilas: [
          { id: 'bogura-sadar', name: 'Bogura Sadar', bnName: 'বগুড়া সদর' },
          { id: 'adamdighi', name: 'Adamdighi', bnName: 'আদমদীঘি' },
          { id: 'dhunat', name: 'Dhunat', bnName: 'ধুনট' },
          { id: 'dupchanchia', name: 'Dupchanchia', bnName: 'দুপচাঁচিয়া' },
          { id: 'gabtali', name: 'Gabtali', bnName: 'গাবতলী' },
          { id: 'kahaloo', name: 'Kahaloo', bnName: 'কাহালু' },
          { id: 'nandigram', name: 'Nandigram', bnName: 'নন্দীগ্রাম' },
          { id: 'sahajanpur', name: 'Sahajanpur', bnName: 'শাজাহানপুর' },
          { id: 'sariakandi', name: 'Sariakandi', bnName: 'সারিয়াকান্দি' },
          { id: 'sherpur-bogura', name: 'Sherpur', bnName: 'শেরপুর' },
          { id: 'shibganj-bogura', name: 'Shibganj', bnName: 'শিবগঞ্জ' },
          { id: 'sonatala', name: 'Sonatala', bnName: 'সোনাতলা' },
        ],
      },
      {
        id: 'pabna',
        name: 'Pabna',
        bnName: 'পাবনা',
        upazilas: [
          { id: 'pabna-sadar', name: 'Pabna Sadar', bnName: 'পাবনা সদর' },
          { id: 'atgharia', name: 'Atgharia', bnName: 'আটঘরিয়া' },
          { id: 'bera', name: 'Bera', bnName: 'বেড়া' },
          { id: 'bhangura', name: 'Bhangura', bnName: 'ভাঙ্গুড়া' },
          { id: 'chatmohar', name: 'Chatmohar', bnName: 'চাটমোহর' },
          { id: 'ishwardi', name: 'Ishwardi', bnName: 'ঈশ্বরদী' },
          { id: 'santhia', name: 'Santhia', bnName: 'সাঁথিয়া' },
          { id: 'sujanagar', name: 'Sujanagar', bnName: 'সুজানগর' },
        ],
      },
      {
        id: 'sirajganj',
        name: 'Sirajganj',
        bnName: 'সিরাজগঞ্জ',
        upazilas: [
          { id: 'sirajganj-sadar', name: 'Sirajganj Sadar', bnName: 'সিরাজগঞ্জ সদর' },
          { id: 'belkuchi', name: 'Belkuchi', bnName: 'বেলকুচি' },
          { id: 'kamarkhanda', name: 'Kamarkhanda', bnName: 'কামারখন্দ' },
          { id: 'kazipur', name: 'Kazipur', bnName: 'কাজীপুর' },
          { id: 'raiganj', name: 'Raiganj', bnName: 'রায়গঞ্জ' },
          { id: 'shahjadpur', name: 'Shahjadpur', bnName: 'শাহজাদপুর' },
          { id: 'tarash', name: 'Tarash', bnName: 'তাড়াশ' },
          { id: 'ullahpara', name: 'Ullahpara', bnName: 'উল্লাপাড়া' },
        ],
      },
      {
        id: 'naogaon',
        name: 'Naogaon',
        bnName: 'নওগাঁ',
        upazilas: [
          { id: 'naogaon-sadar', name: 'Naogaon Sadar', bnName: 'নওগাঁ সদর' },
          { id: 'atrai', name: 'Atrai', bnName: 'আত্রাই' },
          { id: 'badalgachhi', name: 'Badalgachhi', bnName: 'বদলগাছী' },
          { id: 'dhamoirhat', name: 'Dhamoirhat', bnName: 'ধামইরহাট' },
          { id: 'manda', name: 'Manda', bnName: 'মান্দা' },
          { id: 'mohadevpur', name: 'Mohadevpur', bnName: 'মহাদেবপুর' },
          { id: 'niamatpur', name: 'Niamatpur', bnName: 'নিয়ামতপুর' },
          { id: 'patnitala', name: 'Patnitala', bnName: 'পত্নীতলা' },
          { id: 'porsha', name: 'Porsha', bnName: 'পোরশা' },
          { id: 'raninagar', name: 'Raninagar', bnName: 'রাণীনগর' },
          { id: 'sapahar', name: 'Sapahar', bnName: 'সাপাহার' },
        ],
      },
      {
        id: 'natore',
        name: 'Natore',
        bnName: 'নাটোর',
        upazilas: [
          { id: 'natore-sadar', name: 'Natore Sadar', bnName: 'নাটোর সদর' },
          { id: 'bagatipara', name: 'Bagatipara', bnName: 'বাগাতিপাড়া' },
          { id: 'baraigram', name: 'Baraigram', bnName: 'বড়াইগ্রাম' },
          { id: 'gurudaspur', name: 'Gurudaspur', bnName: 'গুরুদাসপুর' },
          { id: 'lalpur', name: 'Lalpur', bnName: 'লালপুর' },
          { id: 'singra', name: 'Singra', bnName: 'সিংড়া' },
          { id: 'naldanga', name: 'Naldanga', bnName: 'নলডাঙ্গা' },
        ],
      },
      {
        id: 'chapainawabganj',
        name: 'Chapainawabganj',
        bnName: 'চাঁপাইনবাবগঞ্জ',
        upazilas: [
          { id: 'chapainawabganj-sadar', name: 'Chapainawabganj Sadar', bnName: 'চাঁপাইনবাবগঞ্জ সদর' },
          { id: 'bholahat', name: 'Bholahat', bnName: 'ভোলাহাট' },
          { id: 'gomastapur', name: 'Gomastapur', bnName: 'গোমস্তাপুর' },
          { id: 'nachole', name: 'Nachole', bnName: 'নাচোল' },
          { id: 'shibganj-chapai', name: 'Shibganj', bnName: 'শিবগঞ্জ' },
        ],
      },
      {
        id: 'joypurhat',
        name: 'Joypurhat',
        bnName: 'জয়পুরহাট',
        upazilas: [
          { id: 'joypurhat-sadar', name: 'Joypurhat Sadar', bnName: 'জয়পুরহাট সদর' },
          { id: 'akkelpur', name: 'Akkelpur', bnName: 'আক্কেলপুর' },
          { id: 'kalai', name: 'Kalai', bnName: 'কালাই' },
          { id: 'khetlal', name: 'Khetlal', bnName: 'ক্ষেতলাল' },
          { id: 'panchbibi', name: 'Panchbibi', bnName: 'পাঁচবিবি' },
        ],
      },
    ],
  },
  {
    id: 'khulna',
    name: 'Khulna Division',
    bnName: 'খুলনা বিভাগ',
    districts: [
      {
        id: 'khulna',
        name: 'Khulna',
        bnName: 'খুলনা',
        upazilas: [
          { id: 'khulna-sadar', name: 'Khulna Sadar', bnName: 'খুলনা সদর' },
          { id: 'sonadanga', name: 'Sonadanga', bnName: 'সোনাডাঙ্গা' },
          { id: 'khalishpur', name: 'Khalishpur', bnName: 'খালিশপুর' },
          { id: 'daulatpur-khulna', name: 'Daulatpur', bnName: 'দৌলতপুর' },
          { id: 'batiaghata', name: 'Batiaghata', bnName: 'বটিয়াঘাটা' },
          { id: 'dacope', name: 'Dacope', bnName: 'দাকোপ' },
          { id: 'dumuria', name: 'Dumuria', bnName: 'ডুমুরিয়া' },
          { id: 'koyra', name: 'Koyra', bnName: 'কয়রা' },
          { id: 'paikgachha', name: 'Paikgachha', bnName: 'পাইকগাছা' },
          { id: 'phultala', name: 'Phultala', bnName: 'ফুলতলা' },
          { id: 'rupsha', name: 'Rupsha', bnName: 'রূপসা' },
        ],
      },
      {
        id: 'jashore',
        name: 'Jashore',
        bnName: 'যশোর',
        upazilas: [
          { id: 'jashore-sadar', name: 'Jashore Sadar', bnName: 'যশোর সদর' },
          { id: 'abhaynagar', name: 'Abhaynagar', bnName: 'অভয়নগর' },
          { id: 'bagherpara', name: 'Bagherpara', bnName: 'বাঘারপাড়া' },
          { id: 'chaugachha', name: 'Chaugachha', bnName: 'চৌগাছা' },
          { id: 'jhikargachha', name: 'Jhikargachha', bnName: 'ঝিকরগাছা' },
          { id: 'keshabpur', name: 'Keshabpur', bnName: 'কেশবপুর' },
          { id: 'manirampur', name: 'Manirampur', bnName: 'মণিরামপুর' },
          { id: 'sharsha', name: 'Sharsha', bnName: 'শার্শা' },
        ],
      },
      {
        id: 'kushtia',
        name: 'Kushtia',
        bnName: 'কুষ্টিয়া',
        upazilas: [
          { id: 'kushtia-sadar', name: 'Kushtia Sadar', bnName: 'কুষ্টিয়া সদর' },
          { id: 'bheramara', name: 'Bheramara', bnName: 'ভেড়ামারা' },
          { id: 'daulatpur-kushtia', name: 'Daulatpur', bnName: 'দৌলতপুর' },
          { id: 'khoksa', name: 'Khoksa', bnName: 'খোকসা' },
          { id: 'kumarkhali', name: 'Kumarkhali', bnName: 'কুমারখালী' },
          { id: 'mirpur-kushtia', name: 'Mirpur', bnName: 'মিরপুর' },
        ],
      },
      {
        id: 'jhenaidah',
        name: 'Jhenaidah',
        bnName: 'ঝিনাইদহ',
        upazilas: [
          { id: 'jhenaidah-sadar', name: 'Jhenaidah Sadar', bnName: 'ঝিনাইদহ সদর' },
          { id: 'harinakunda', name: 'Harinakunda', bnName: 'হরিণাকুণ্ডু' },
          { id: 'kaliganj-jhenaidah', name: 'Kaliganj', bnName: 'কালীগঞ্জ' },
          { id: 'kotchandpur', name: 'Kotchandpur', bnName: 'কোটচাঁদপুর' },
          { id: 'maheshpur', name: 'Maheshpur', bnName: 'মহেশপুর' },
          { id: 'shailkupa', name: 'Shailkupa', bnName: 'শৈলকুপা' },
        ],
      },
      {
        id: 'satkhira',
        name: 'Satkhira',
        bnName: 'সাতক্ষীরা',
        upazilas: [
          { id: 'satkhira-sadar', name: 'Satkhira Sadar', bnName: 'সাতক্ষীরা সদর' },
          { id: 'assasuni', name: 'Assasuni', bnName: 'আশাশুনি' },
          { id: 'debhata', name: 'Debhata', bnName: 'দেবহাটা' },
          { id: 'kalaroa', name: 'Kalaroa', bnName: 'কলারোয়া' },
          { id: 'kaliganj-satkhira', name: 'Kaliganj', bnName: 'কালীগঞ্জ' },
          { id: 'shyamnagar', name: 'Shyamnagar', bnName: 'শ্যামনগর' },
          { id: 'tala', name: 'Tala', bnName: 'তালা' },
        ],
      },
      {
        id: 'bagerhat',
        name: 'Bagerhat',
        bnName: 'বাগেরহাট',
        upazilas: [
          { id: 'bagerhat-sadar', name: 'Bagerhat Sadar', bnName: 'বাগেরহাট সদর' },
          { id: 'chitalmari', name: 'Chitalmari', bnName: 'চিতলমারী' },
          { id: 'fakirhat', name: 'Fakirhat', bnName: 'ফকিরহাট' },
          { id: 'kachua-bagerhat', name: 'Kachua', bnName: 'কচুয়া' },
          { id: 'mollahat', name: 'Mollahat', bnName: 'মোল্লাহাট' },
          { id: 'mongla', name: 'Mongla', bnName: 'মংলা' },
          { id: 'morrelganj', name: 'Morrelganj', bnName: 'মোড়েলগঞ্জ' },
          { id: 'rampal', name: 'Rampal', bnName: 'রামপাল' },
          { id: 'sarankhola', name: 'Sarankhola', bnName: 'শরণখোলা' },
        ],
      },
      {
        id: 'chuadanga',
        name: 'Chuadanga',
        bnName: 'চুয়াডাঙ্গা',
        upazilas: [
          { id: 'chuadanga-sadar', name: 'Chuadanga Sadar', bnName: 'চুয়াডাঙ্গা সদর' },
          { id: 'alamdanga', name: 'Alamdanga', bnName: 'আলমডাঙ্গা' },
          { id: 'damurhuda', name: 'Damurhuda', bnName: 'দামুড়হুদা' },
          { id: 'jibannagar', name: 'Jibannagar', bnName: 'জীবননগর' },
        ],
      },
      {
        id: 'meherpur',
        name: 'Meherpur',
        bnName: 'মেহেরপুর',
        upazilas: [
          { id: 'meherpur-sadar', name: 'Meherpur Sadar', bnName: 'মেহেরপুর সদর' },
          { id: 'gangni', name: 'Gangni', bnName: 'গাংনী' },
          { id: 'mujibnagar', name: 'Mujibnagar', bnName: 'মুজিবনগর' },
        ],
      },
      {
        id: 'magura',
        name: 'Magura',
        bnName: 'মাগুরা',
        upazilas: [
          { id: 'magura-sadar', name: 'Magura Sadar', bnName: 'মাগুরা সদর' },
          { id: 'mohammadpur-magura', name: 'Mohammadpur', bnName: 'মহম্মদপুর' },
          { id: 'shalikha', name: 'Shalikha', bnName: 'শালিখা' },
          { id: 'sreepur-magura', name: 'Sreepur', bnName: 'শ্রীপুর' },
        ],
      },
      {
        id: 'narail',
        name: 'Narail',
        bnName: 'নড়াইল',
        upazilas: [
          { id: 'narail-sadar', name: 'Narail Sadar', bnName: 'নড়াইল সদর' },
          { id: 'kalia', name: 'Kalia', bnName: 'কালিয়া' },
          { id: 'lohagara-narail', name: 'Lohagara', bnName: 'লোহাগড়া' },
        ],
      },
    ],
  },
  {
    id: 'barishal',
    name: 'Barishal Division',
    bnName: 'বরিশাল বিভাগ',
    districts: [
      {
        id: 'barishal',
        name: 'Barishal',
        bnName: 'বরিশাল',
        upazilas: [
          { id: 'barishal-sadar', name: 'Barishal Sadar', bnName: 'বরিশাল সদর' },
          { id: 'agailjhara', name: 'Agailjhara', bnName: 'আগৈলঝাড়া' },
          { id: 'babuganj', name: 'Babuganj', bnName: 'বাবুগঞ্জ' },
          { id: 'bakerganj', name: 'Bakerganj', bnName: 'বাকেরগঞ্জ' },
          { id: 'banaripara', name: 'Banaripara', bnName: 'বানারীপাড়া' },
          { id: 'gaurnadi', name: 'Gaurnadi', bnName: 'গৌরনদী' },
          { id: 'hizla', name: 'Hizla', bnName: 'হিজলা' },
          { id: 'mehendiganj', name: 'Mehendiganj', bnName: 'মেহেন্দিগঞ্জ' },
          { id: 'muladi', name: 'Muladi', bnName: 'মুলাদী' },
          { id: 'wazirpur', name: 'Wazirpur', bnName: 'উজিরপুর' },
        ],
      },
      {
        id: 'patuakhali',
        name: 'Patuakhali',
        bnName: 'পটুয়াখালী',
        upazilas: [
          { id: 'patuakhali-sadar', name: 'Patuakhali Sadar', bnName: 'পটুয়াখালী সদর' },
          { id: 'bauphal', name: 'Bauphal', bnName: 'বাউফল' },
          { id: 'dashmina', name: 'Dashmina', bnName: 'দশমিনা' },
          { id: 'dumki', name: 'Dumki', bnName: 'দুমকি' },
          { id: 'galachipa', name: 'Galachipa', bnName: 'গলাচিপা' },
          { id: 'kalapara', name: 'Kalapara', bnName: 'কলাপাড়া' },
          { id: 'mirzaganj', name: 'Mirzaganj', bnName: 'মির্জাগঞ্জ' },
          { id: 'rangabali', name: 'Rangabali', bnName: 'রাঙ্গাবালী' },
        ],
      },
      {
        id: 'bhola',
        name: 'Bhola',
        bnName: 'ভোলা',
        upazilas: [
          { id: 'bhola-sadar', name: 'Bhola Sadar', bnName: 'ভোলা সদর' },
          { id: 'burhanuddin', name: 'Burhanuddin', bnName: 'বোরহানউদ্দিন' },
          { id: 'char-fasson', name: 'Char Fasson', bnName: 'চরফ্যাশন' },
          { id: 'daulatkhan', name: 'Daulatkhan', bnName: 'দৌলতখান' },
          { id: 'lalmohan', name: 'Lalmohan', bnName: 'লালমোহন' },
          { id: 'manpura', name: 'Manpura', bnName: 'মনপুরা' },
          { id: 'tazumuddin', name: 'Tazumuddin', bnName: 'তজুমদ্দিন' },
        ],
      },
      {
        id: 'pirojpur',
        name: 'Pirojpur',
        bnName: 'পিরোজপুর',
        upazilas: [
          { id: 'pirojpur-sadar', name: 'Pirojpur Sadar', bnName: 'পিরোজপুর সদর' },
          { id: 'bhandaria', name: 'Bhandaria', bnName: 'ভান্ডারিয়া' },
          { id: 'kawkhali-pirojpur', name: 'Kawkhali', bnName: 'কাউখালী' },
          { id: 'mathbaria', name: 'Mathbaria', bnName: 'মঠবাড়ীয়া' },
          { id: 'nazirpur', name: 'Nazirpur', bnName: 'নাজিরপুর' },
          { id: 'nesarabad', name: 'Nesarabad (Swarupkathi)', bnName: 'নেছারাবাদ (স্বরূপকাঠি)' },
          { id: 'indurkani', name: 'Indurkani', bnName: 'ইন্দুরকানী' },
        ],
      },
      {
        id: 'barguna',
        name: 'Barguna',
        bnName: 'বরগুনা',
        upazilas: [
          { id: 'barguna-sadar', name: 'Barguna Sadar', bnName: 'বরগুনা সদর' },
          { id: 'amtali', name: 'Amtali', bnName: 'আমতলী' },
          { id: 'bamna', name: 'Bamna', bnName: 'বামনা' },
          { id: 'betagi', name: 'Betagi', bnName: 'বেতাগী' },
          { id: 'patharghata', name: 'Patharghata', bnName: 'পাথরঘাটা' },
          { id: 'taltali', name: 'Taltali', bnName: 'তালতলী' },
        ],
      },
      {
        id: 'jhalokathi',
        name: 'Jhalokathi',
        bnName: 'ঝালকাঠি',
        upazilas: [
          { id: 'jhalokathi-sadar', name: 'Jhalokathi Sadar', bnName: 'ঝালকাঠি সদর' },
          { id: 'kathalia', name: 'Kathalia', bnName: 'কাঠালিয়া' },
          { id: 'nalchity', name: 'Nalchity', bnName: 'নলছিটি' },
          { id: 'rajapur', name: 'Rajapur', bnName: 'রাজাপুর' },
        ],
      },
    ],
  },
  {
    id: 'sylhet',
    name: 'Sylhet Division',
    bnName: 'সিলেট বিভাগ',
    districts: [
      {
        id: 'sylhet',
        name: 'Sylhet',
        bnName: 'সিলেট',
        upazilas: [
          { id: 'sylhet-sadar', name: 'Sylhet Sadar', bnName: 'সিলেট সদর' },
          { id: 'beanibazar', name: 'Beanibazar', bnName: 'বিয়ানীবাজার' },
          { id: 'bishwanath', name: 'Bishwanath', bnName: 'বিশ্বনাথ' },
          { id: 'companiganj-sylhet', name: 'Companiganj', bnName: 'কোম্পানীগঞ্জ' },
          { id: 'dakshin-surma', name: 'Dakshin Surma', bnName: 'দক্ষিণ সুরমা' },
          { id: 'fenchuganj', name: 'Fenchuganj', bnName: 'ফেঞ্চুগঞ্জ' },
          { id: 'golapganj', name: 'Golapganj', bnName: 'গোলাপগঞ্জ' },
          { id: 'gowainghat', name: 'Gowainghat', bnName: 'গোয়াইনঘাট' },
          { id: 'jaintiapur', name: 'Jaintiapur', bnName: 'জৈন্তাপুর' },
          { id: 'kanaighat', name: 'Kanaighat', bnName: 'কানাইঘাট' },
          { id: 'osmani-nagar', name: 'Osmani Nagar', bnName: 'ওসমানী নগর' },
          { id: 'zakiganj', name: 'Zakiganj', bnName: 'জকিগঞ্জ' },
        ],
      },
      {
        id: 'moulvibazar',
        name: 'Moulvibazar',
        bnName: 'মৌলভীবাজার',
        upazilas: [
          { id: 'moulvibazar-sadar', name: 'Moulvibazar Sadar', bnName: 'মৌলভীবাজার সদর' },
          { id: 'barlekha', name: 'Barlekha', bnName: 'বড়লেখা' },
          { id: 'juri', name: 'Juri', bnName: 'জুড়ী' },
          { id: 'kamalganj', name: 'Kamalganj', bnName: 'কমলগঞ্জ' },
          { id: 'kulaura', name: 'Kulaura', bnName: 'কুলাউড়া' },
          { id: 'rajnagar', name: 'Rajnagar', bnName: 'রাজনগর' },
          { id: 'sreemangal', name: 'Sreemangal', bnName: 'শ্রীমঙ্গল' },
        ],
      },
      {
        id: 'habiganj',
        name: 'Habiganj',
        bnName: 'হবিগঞ্জ',
        upazilas: [
          { id: 'habiganj-sadar', name: 'Habiganj Sadar', bnName: 'হবিগঞ্জ সদর' },
          { id: 'ajmiriganj', name: 'Ajmiriganj', bnName: 'আজমিরীগঞ্জ' },
          { id: 'bahubal', name: 'Bahubal', bnName: 'বাহুবল' },
          { id: 'baniyachong', name: 'Baniyachong', bnName: 'বানিয়াচং' },
          { id: 'chunarughat', name: 'Chunarughat', bnName: 'চুনারুঘাট' },
          { id: 'lakhai', name: 'Lakhai', bnName: 'লাখাই' },
          { id: 'madhabpur', name: 'Madhabpur', bnName: 'মাধবপুর' },
          { id: 'nabiganj', name: 'Nabiganj', bnName: 'নবীগঞ্জ' },
          { id: 'sayestaganj', name: 'Sayestaganj', bnName: 'শায়েস্তাগঞ্জ' },
        ],
      },
      {
        id: 'sunamganj',
        name: 'Sunamganj',
        bnName: 'সুনামগঞ্জ',
        upazilas: [
          { id: 'sunamganj-sadar', name: 'Sunamganj Sadar', bnName: 'সুনামগঞ্জ সদর' },
          { id: 'bishwamvarpur', name: 'Bishwamvarpur', bnName: 'বিশ্বম্ভরপুর' },
          { id: 'chhatak', name: 'Chhatak', bnName: 'ছাতক' },
          { id: 'derai', name: 'Derai', bnName: 'দিরাই' },
          { id: 'dharamapasha', name: 'Dharamapasha', bnName: 'ধর্মপাশা' },
          { id: 'dowarabazar', name: 'Dowarabazar', bnName: 'দোয়ারাবাজার' },
          { id: 'jagannathpur', name: 'Jagannathpur', bnName: 'জগন্নাথপুর' },
          { id: 'jamalganj', name: 'Jamalganj', bnName: 'জামালগঞ্জ' },
          { id: 'sullah', name: 'Sullah', bnName: 'শাল্লা' },
          { id: 'tahirpur', name: 'Tahirpur', bnName: 'তাহিরপুর' },
          { id: 'shantiganj', name: 'Shantiganj', bnName: 'শান্তিগঞ্জ' },
        ],
      },
    ],
  },
  {
    id: 'rangpur',
    name: 'Rangpur Division',
    bnName: 'রংপুর বিভাগ',
    districts: [
      {
        id: 'rangpur',
        name: 'Rangpur',
        bnName: 'রংপুর',
        upazilas: [
          { id: 'rangpur-sadar', name: 'Rangpur Sadar', bnName: 'রংপুর সদর' },
          { id: 'badarganj', name: 'Badarganj', bnName: 'বদরগঞ্জ' },
          { id: 'gangachara', name: 'Gangachara', bnName: 'গংগাচড়া' },
          { id: 'kaunia', name: 'Kaunia', bnName: 'কাউনিয়া' },
          { id: 'mithapukur', name: 'Mithapukur', bnName: 'মিঠাপুকুর' },
          { id: 'pirgachha', name: 'Pirgachha', bnName: 'পীরগাছা' },
          { id: 'pirganj-rangpur', name: 'Pirganj', bnName: 'পীরগঞ্জ' },
          { id: 'taraganj', name: 'Taraganj', bnName: 'তারাগঞ্জ' },
        ],
      },
      {
        id: 'dinajpur',
        name: 'Dinajpur',
        bnName: 'দিনাজপুর',
        upazilas: [
          { id: 'dinajpur-sadar', name: 'Dinajpur Sadar', bnName: 'দিনাজপুর সদর' },
          { id: 'birampur', name: 'Birampur', bnName: 'বিরামপুর' },
          { id: 'birganj', name: 'Birganj', bnName: 'বীরগঞ্জ' },
          { id: 'birol', name: 'Birol', bnName: 'বিরল' },
          { id: 'bochaganj', name: 'Bochaganj', bnName: 'বোচাগঞ্জ' },
          { id: 'chirirbandar', name: 'Chirirbandar', bnName: 'চিরিরবন্দর' },
          { id: 'fulbari-dinajpur', name: 'Fulbari', bnName: 'ফুলবাড়ী' },
          { id: 'ghoraghat', name: 'Ghoraghat', bnName: 'ঘোড়াঘাট' },
          { id: 'hakimpur', name: 'Hakimpur', bnName: 'হাকিমপুর' },
          { id: 'kaharole', name: 'Kaharole', bnName: 'কাহারোল' },
          { id: 'khansama', name: 'Khansama', bnName: 'খানসামা' },
          { id: 'nawabganj-dinajpur', name: 'Nawabganj', bnName: 'নবাবগঞ্জ' },
          { id: 'parbatipur', name: 'Parbatipur', bnName: 'পার্বতীপুর' },
        ],
      },
      {
        id: 'gaibandha',
        name: 'Gaibandha',
        bnName: 'গাইবান্ধা',
        upazilas: [
          { id: 'gaibandha-sadar', name: 'Gaibandha Sadar', bnName: 'গাইবান্ধা সদর' },
          { id: 'fulchhari', name: 'Fulchhari', bnName: 'ফুলছড়ি' },
          { id: 'gobindaganj', name: 'Gobindaganj', bnName: 'গোবিন্দগঞ্জ' },
          { id: 'palashbari', name: 'Palashbari', bnName: 'পলাশবাড়ী' },
          { id: 'sadullapur', name: 'Sadullapur', bnName: 'সাদুল্লাপুর' },
          { id: 'sughatta', name: 'Sughatta', bnName: 'সাঘাটা' },
          { id: 'sundarganj', name: 'Sundarganj', bnName: 'সুন্দরগঞ্জ' },
        ],
      },
      {
        id: 'kurigram',
        name: 'Kurigram',
        bnName: 'কুড়িগ্রাম',
        upazilas: [
          { id: 'kurigram-sadar', name: 'Kurigram Sadar', bnName: 'কুড়িগ্রাম সদর' },
          { id: 'bhurungamari', name: 'Bhurungamari', bnName: 'ভুরুঙ্গামারী' },
          { id: 'char-rajibpur', name: 'Char Rajibpur', bnName: 'চর রাজিবপুর' },
          { id: 'chilmari', name: 'Chilmari', bnName: 'চিলমারী' },
          { id: 'nageshwari', name: 'Nageshwari', bnName: 'নাগেশ্বরী' },
          { id: 'phulbari-kurigram', name: 'Phulbari', bnName: 'ফুলবাড়ী' },
          { id: 'rajarhat', name: 'Rajarhat', bnName: 'রাজারহাট' },
          { id: 'raomari', name: 'Raomari', bnName: 'রৌমারী' },
          { id: 'ulipur', name: 'Ulipur', bnName: 'উলিপুর' },
        ],
      },
      {
        id: 'nilphamari',
        name: 'Nilphamari',
        bnName: 'নীলফামারী',
        upazilas: [
          { id: 'nilphamari-sadar', name: 'Nilphamari Sadar', bnName: 'নীলফামারী সদর' },
          { id: 'dimla', name: 'Dimla', bnName: 'ডিমলা' },
          { id: 'domar', name: 'Domar', bnName: 'ডোমার' },
          { id: 'jaldhaka', name: 'Jaldhaka', bnName: 'জলঢাকা' },
          { id: 'kishoreganj-nilphamari', name: 'Kishoreganj', bnName: 'কিশোরগঞ্জ' },
          { id: 'syedpur', name: 'Syedpur', bnName: 'সৈয়দপুর' },
        ],
      },
      {
        id: 'lalmonirhat',
        name: 'Lalmonirhat',
        bnName: 'লালমনিরহাট',
        upazilas: [
          { id: 'lalmonirhat-sadar', name: 'Lalmonirhat Sadar', bnName: 'লালমনিরহাট সদর' },
          { id: 'aditmari', name: 'Aditmari', bnName: 'আদিতমারী' },
          { id: 'hatibandha', name: 'Hatibandha', bnName: 'হাতীবান্ধা' },
          { id: 'kaliganj-lalmonirhat', name: 'Kaliganj', bnName: 'কালীগঞ্জ' },
          { id: 'patgram', name: 'Patgram', bnName: 'পাটগ্রাম' },
        ],
      },
      {
        id: 'thakurgaon',
        name: 'Thakurgaon',
        bnName: 'ঠাকুরগাঁও',
        upazilas: [
          { id: 'thakurgaon-sadar', name: 'Thakurgaon Sadar', bnName: 'ঠাকুরগাঁও সদর' },
          { id: 'baliadangi', name: 'Baliadangi', bnName: 'বালিয়াডাঙ্গী' },
          { id: 'haripur', name: 'Haripur', bnName: 'হরিপুর' },
          { id: 'pirganj-thakurgaon', name: 'Pirganj', bnName: 'পীরগঞ্জ' },
          { id: 'ranisankail', name: 'Ranisankail', bnName: 'রাণীশংকৈল' },
        ],
      },
      {
        id: 'panchagarh',
        name: 'Panchagarh',
        bnName: 'পঞ্চগড়',
        upazilas: [
          { id: 'panchagarh-sadar', name: 'Panchagarh Sadar', bnName: 'পঞ্চগড় সদর' },
          { id: 'atwari', name: 'Atwari', bnName: 'আটোয়ারী' },
          { id: 'boda', name: 'Boda', bnName: 'বোদা' },
          { id: 'debiganj', name: 'Debiganj', bnName: 'দেবীগঞ্জ' },
          { id: 'tetulia', name: 'Tetulia', bnName: 'তেঁতুলিয়া' },
        ],
      },
    ],
  },
  {
    id: 'mymensingh',
    name: 'Mymensingh Division',
    bnName: 'ময়মনসিংহ বিভাগ',
    districts: [
      {
        id: 'mymensingh',
        name: 'Mymensingh',
        bnName: 'ময়মনসিংহ',
        upazilas: [
          { id: 'mymensingh-sadar', name: 'Mymensingh Sadar', bnName: 'ময়মনসিংহ সদর' },
          { id: 'bhaluka', name: 'Bhaluka', bnName: 'ভালুকা' },
          { id: 'dhobaura', name: 'Dhobaura', bnName: 'ধোবাউড়া' },
          { id: 'fulbaria', name: 'Fulbaria', bnName: 'ফুলবাড়ীয়া' },
          { id: 'gaffargaon', name: 'Gaffargaon', bnName: 'গফরগাঁও' },
          { id: 'gauripur', name: 'Gauripur', bnName: 'গৌরীপুর' },
          { id: 'haluaghat', name: 'Haluaghat', bnName: 'হালুয়াঘাট' },
          { id: 'ishwarganj', name: 'Ishwarganj', bnName: 'ঈশ্বরগঞ্জ' },
          { id: 'muktagachha', name: 'Muktagachha', bnName: 'মুক্তাগাছা' },
          { id: 'nandail', name: 'Nandail', bnName: 'নান্দাইল' },
          { id: 'phulpur', name: 'Phulpur', bnName: 'ফুলপুর' },
          { id: 'tara-khanda', name: 'Tarakanda', bnName: 'তারাকান্দা' },
          { id: 'trishal', name: 'Trishal', bnName: 'ত্রিশাল' },
        ],
      },
      {
        id: 'jamalpur',
        name: 'Jamalpur',
        bnName: 'জামালপুর',
        upazilas: [
          { id: 'jamalpur-sadar', name: 'Jamalpur Sadar', bnName: 'জামালপুর সদর' },
          { id: 'bakshiganj', name: 'Bakshiganj', bnName: 'বকশীগঞ্জ' },
          { id: 'dewanganj', name: 'Dewanganj', bnName: 'দেওয়ানগঞ্জ' },
          { id: 'islampur', name: 'Islampur', bnName: 'ইসলামপুর' },
          { id: 'madarganj', name: 'Madarganj', bnName: 'মাদারগঞ্জ' },
          { id: 'melandaha', name: 'Melandaha', bnName: 'মেলান্দহ' },
          { id: 'sarishabari', name: 'Sarishabari', bnName: 'সরিষাবাড়ী' },
        ],
      },
      {
        id: 'netrokona',
        name: 'Netrokona',
        bnName: 'নেত্রকোণা',
        upazilas: [
          { id: 'netrokona-sadar', name: 'Netrokona Sadar', bnName: 'নেত্রকোণা সদর' },
          { id: 'atpara', name: 'Atpara', bnName: 'আটপাড়া' },
          { id: 'barhatta', name: 'Barhatta', bnName: 'বারহাট্টা' },
          { id: 'durgapur-netro', name: 'Durgapur', bnName: 'দুর্গাপুর' },
          { id: 'kalmakanda', name: 'Kalmakanda', bnName: 'কলমাকান্দা' },
          { id: 'kendua', name: 'Kendua', bnName: 'কেন্দুয়া' },
          { id: 'madan', name: 'Madan', bnName: 'মদন' },
          { id: 'mohanganj', name: 'Mohanganj', bnName: 'মোহনগঞ্জ' },
          { id: 'purbadhala', name: 'Purbadhala', bnName: 'পূর্বধলা' },
          { id: 'khaliajuri', name: 'Khaliajuri', bnName: 'খালিয়াজুরী' },
        ],
      },
      {
        id: 'sherpur',
        name: 'Sherpur',
        bnName: 'শেরপুর',
        upazilas: [
          { id: 'sherpur-sadar', name: 'Sherpur Sadar', bnName: 'শেরপুর সদর' },
          { id: 'jhenaigati', name: 'Jhenaigati', bnName: 'ঝিনাইগাতী' },
          { id: 'nakla', name: 'Nakla', bnName: 'নকলা' },
          { id: 'nalitabari', name: 'Nalitabari', bnName: 'নালিতাবাড়ী' },
          { id: 'sreebardi', name: 'Sreebardi', bnName: 'শ্রীবরদী' },
        ],
      },
    ],
  },
];
